/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package examples

class App {
    fun runExamples() {
        runLpSolveExample()
    }
}

fun main() {
    App().runExamples()
}
