/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package examples

class App {
    fun runExamples() {
        runLpSolveExample()
        OrtoolsExample().runExample()
    }

    val testValue = 2  // for use in a sample test.
}

fun main() {
    App().runExamples()
}

