/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package examples

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testAppHasRunExamples() {
        val classUnderTest = App()
        assertEquals(classUnderTest.testValue, 2)
    }
}
